Add files
it-top-shambala/html_home_work_1 pull request #1
Opened 2022-06-27 16:12 UTC by Scrudje

ДЗ по HTML Красников А.В.

2022-06-28 17:31 UTC, anst-foto requested changes
Есть замечания по вёрстке

2022-06-28 17:31 UTC, anst-foto commented on index.html
> +
Не все теги закрываются

2022-06-28 17:31 UTC, anst-foto commented on index.html
> +                        <strong>•	 Технические навыки.</strong> Общий стаж работы на действующем производстве – более 20 лет. Навыки организации деятельности производственной службы. Организация эксп
Можно было бы использовать маркированный список `<ul>`

2022-06-28 17:31 UTC, anst-foto commented on index.html
> +                                <br>• Разработка ППР, технологических карт на выполнение работ по ППР.
Плохой вариант с оформлением списка через `<br/>`

2022-06-29 17:59 UTC, Scrudje commented
Добрый день! По первому замечанию, не понял, какие именно теги не закрыты? Вроде как теги <col> и <img> не должны закрываться, а остальные закрыты..
Остальные замечания по верстке поправил.

2022-06-29 17:59 UTC, closed without merging